addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.16")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "6.5.0")
addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.204")
